[default]
ckp_dir = '/home/andompesta/Projects/omnitext/checkpoint'
run_dir = '/home/andompesta/Projects/omnitext/run'
data_dir = '/home/andompesta/Projects/omnitext/data'
exp_dir = '/home/andompesta/Projects/omnitext/export'